[workspace]
resolver = "2"

members = [
    # "contracts/hub/*",
    "contracts/liquidity/*",
    "contracts/common/*",
    "packages/*",
    "./proxy-contract"
    # "tests-integration",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true

[workspace.dependencies]
euclid = { path = "./packages/euclid" }
euclid-ibc = { path = "./packages/euclid_ibc" }
euclid-utils = { path = "./packages/euclid_utils" }

cosmwasm-schema = "2.1.5"
snip20-reference-impl ={ path = "./packages/snip20-reference-impl/"}
schemars = { version = "0.8.21" }
serde = { version = "1.0.216" }
thiserror = { version = "2.0.6" }
# itertools = "0.13.0"

mock = { path = "./packages/mock" }
secret-toolkit = { version = "0.10.2", features = [
  "utils",
  "serialization",
  "viewing-key",
  "permit",
  "storage",
  "snip20",
  "snip721",
] }

cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.1.10", features = [
  "stargate",
  "staking",
  "ibc3",
  "random",
]}
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "1.0.0"}
secret-storage-plus = { git = "https://github.com/securesecrets/secret-plus-utils", version = "0.13.4", branch = "main"}
secret-utils = { git = "https://github.com/securesecrets/secret-plus-utils", version = "0.13.4", branch = "main" }
secret-cw2 = { git = "https://github.com/securesecrets/secret-plus-utils", version = "1.0.1", branch = "main"}
anybuf = "0.5.2"
secret-multi-test = { git = "https://github.com/kent-3/secret-plus-utils", branch = "protobuf-fix"}
shade-protocol = { git = "https://github.com/securesecrets/shade", rev = "lend-v1" ,features = [
  "query_auth_impl",
  "admin","basic_staking"
] }
shade-multi-test = { git = "https://github.com/securesecrets/shade",features = [ "query_auth", "admin"  ] }
proxy = { path = "./proxy-contract/"}