[workspace]
resolver = "2"

members = [
    "contracts/hub/*",
    "contracts/hub_utilities/*",
    "contracts/liquidity/*",
    "contracts/common/*",
    "packages/*",
    "tests-integration",
    "tests-fuzz",
    "tools/schema-to-proto",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true

[workspace.dependencies]
euclid = { path = "./packages/euclid" }
euclid-pool = { path = "./packages/pool" }
euclid-ibc = { path = "./packages/euclid_ibc" }
euclid-encoding = { path = "./packages/euclid_encoding" }
euclid-utils = { path = "./packages/euclid_utils" }
forwarding = { path = "./packages/forwarding" }
relayer = { path = "./packages/relayer" }

cosmwasm-std = "2.2.2"
cosmwasm-schema = "2.2.2"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
cw2 = "2.0.0"
cw20 = "2.0.0"
cw20-base = "2.0.0"
schemars = "0.8.22"
serde = { version = "1.0.208", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.49" }
itertools = "0.10"
function_name = "0.3"
alloy-sol-types = { version = "=1.6.0", default-features = false }

mock = { path = "./packages/mock" }
cw-multi-test = { version = "2.4.0"}
cw-orch = "0.28.0"
cross-vm-macros = { git = "https://github.com/SlayerAnsh/cross-vm-testing", rev = "de5dd26ed26e68cf21bf9067e8b8619bce46cce6"}
cross-vm-cosmwasm = { git = "https://github.com/SlayerAnsh/cross-vm-testing", rev = "de5dd26ed26e68cf21bf9067e8b8619bce46cce6"}
