[workspace]
resolver = "2"

members = [
    "../packages/euclid",
    "../packages/euclid_ibc",
    "../packages/pool",
    "../packages/mock",
    "../packages/relayer",
    "../contracts/hub/router",
    "../contracts/hub/virtual_balance",
    "../contracts/hub/cp_vlp",
    "../contracts/hub/stable_vlp",
    "../contracts/hub/concentrated_vlp",
    "../contracts/liquidity/factory",
    "../contracts/liquidity/escrow",
    "../contracts/liquidity/lp_token",
    "../contracts/liquidity/position_token",
]

[workspace.dependencies]
euclid = { path = "../packages/euclid" }
euclid-pool = { path = "../packages/pool" }
euclid-ibc = { path = "../packages/euclid_ibc" }
euclid-utils = { path = "../packages/euclid_utils" }
forwarding = { path = "../packages/forwarding" }
relayer = { path = "../packages/relayer" }

cosmwasm-std = "2.2.2"
cosmwasm-schema = "2.2.2"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
cw2 = "2.0.0"
cw20 = "2.0.0"
cw20-base = "2.0.0"
schemars = "0.8.22"
serde = { version = "1.0.208", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.49" }
itertools = "0.10"
function_name = "0.3"

mock = { path = "../packages/mock" }
cw-multi-test = { version = "2.4.0" }
cw-orch = "0.28.0"
