[package]
name = "euclid-ibc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.1" }
cw-storage-plus = "0.15"
itertools = "0.10"
cosmwasm-schema = "1.1"
cw-utils = "1.0"
thiserror = { version = "1.0.49" }
euclid = {workspace = true}