//! Convert `CosmWasm` JSON Schema files to Protocol Buffer (.proto) definitions.
//!
//! Reads contract schema JSON files generated by `cosmwasm_schema::write_api!`
//! and produces `.proto` files for publishing to buf.build.
//!
//! # Usage
//! ```sh
//! cargo run -p schema-to-proto                # Write to proto/
//! cargo run -p schema-to-proto -- --dry-run   # Print without writing
//! ```
//!
//! Generate schemas first:
//! ```sh
//! for d in contracts/*/*/; do
//!     [ -f "$d/src/bin/schema.rs" ] && (cd "$d" && cargo run --bin schema)
//! done
//! ```

use regex::Regex;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

const TYPES_PACKAGE: &str = "euclid.types.v1";
const TYPES_PROTO_PATH: &str = "euclid/types/v1/types.proto";

/// `CosmWasm` types serialized as JSON strings -> proto string
const STRING_NEWTYPES: &[&str] = &[
    "Addr",
    "Binary",
    "ChainUid",
    "Decimal",
    "Timestamp",
    "Token",
    "Uint128",
    "Uint64",
];

fn is_string_newtype_name(name: &str) -> bool {
    STRING_NEWTYPES.contains(&name)
}

// ─── Naming ──────────────────────────────────────────────────────

fn snake_to_pascal(name: &str) -> String {
    name.split('_')
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    upper + chars.as_str()
                }
                None => String::new(),
            }
        })
        .collect()
}

fn sanitize_type_name(name: &str) -> String {
    let mut s = name.to_string();
    for (old, new) in [("_for_", "_For_"), ("_of_", "_Of_"), ("_and_", "_And_")] {
        s = s.replace(old, new);
    }
    s.split('_')
        .map(|seg| {
            if seg.is_empty() {
                String::new()
            } else {
                let mut chars = seg.chars();
                match chars.next() {
                    Some(c) => {
                        let upper: String = c.to_uppercase().collect();
                        upper + chars.as_str()
                    }
                    None => String::new(),
                }
            }
        })
        .collect()
}

fn enum_prefix(pascal_name: &str) -> String {
    let re = Regex::new(r"(?P<b>.)(?P<a>[A-Z])").unwrap();
    re.replace_all(pascal_name, "${b}_${a}").to_uppercase()
}

// ─── Schema classification ──────────────────────────────────────

fn is_string_newtype(s: &Value) -> bool {
    if s.get("type").and_then(Value::as_str) == Some("string") && s.get("enum").is_none() {
        return true;
    }
    if let Some(all_of) = s.get("allOf").and_then(Value::as_array) {
        if all_of.len() == 1 {
            if let Some(r) = all_of[0].get("$ref").and_then(Value::as_str) {
                let ref_name = r.rsplit('/').next().unwrap_or("");
                return is_string_newtype_name(ref_name);
            }
        }
    }
    false
}

fn is_string_enum(s: &Value) -> bool {
    s.get("type").and_then(Value::as_str) == Some("string")
        && s.get("enum")
            .and_then(Value::as_array)
            .is_some_and(|a| !a.is_empty())
}

fn is_empty_enum(s: &Value) -> bool {
    s.get("type").and_then(Value::as_str) == Some("string")
        && s.get("enum")
            .and_then(Value::as_array)
            .is_some_and(Vec::is_empty)
}

fn is_tagged_variant(v: &Value) -> bool {
    if v.get("type").and_then(Value::as_str) == Some("object") {
        if let Some(req) = v.get("required").and_then(Value::as_array) {
            if req.len() == 1 {
                return true;
            }
        }
    }
    // String literal variant: {"type": "string", "enum": ["variant_name"]}
    if v.get("type").and_then(Value::as_str) == Some("string") {
        if let Some(e) = v.get("enum").and_then(Value::as_array) {
            if e.len() == 1 {
                return true;
            }
        }
    }
    false
}

fn is_rust_enum(s: &Value) -> bool {
    match s.get("oneOf").and_then(Value::as_array) {
        Some(variants) => variants.iter().all(is_tagged_variant),
        None => false,
    }
}

fn is_struct(s: &Value) -> bool {
    s.get("type").and_then(Value::as_str) == Some("object")
        && s.get("properties")
            .and_then(Value::as_object)
            .is_some_and(|p| !p.is_empty())
}

fn is_empty_struct(s: &Value) -> bool {
    s.get("type").and_then(Value::as_str) == Some("object")
        && s.get("properties")
            .and_then(Value::as_object)
            .is_none_or(serde_json::Map::is_empty)
        && s.get("additionalProperties")
            .and_then(Value::as_bool)
            .is_some_and(|b| !b)
}

// ─── Type resolution ────────────────────────────────────────────

fn int_format(fmt: &str) -> &str {
    match fmt {
        "uint64" => "uint64",
        "uint128" => "string",
        "int32" => "int32",
        "uint8" | "uint16" | "uint32" => "uint32",
        // "int64" and anything else
        _ => "int64",
    }
}

/// Returns (`proto_type`, modifier) where modifier is "" | "optional" | "repeated".
fn resolve_type(
    schema: &Value,
    defs: &BTreeMap<String, Value>,
    shared: &BTreeMap<String, Value>,
    imports: &mut BTreeSet<String>,
) -> (String, String) {
    if let Some(r) = schema.get("$ref").and_then(Value::as_str) {
        let name = r.rsplit('/').next().unwrap_or("");
        return resolve_ref(name, defs, shared, imports);
    }

    if let Some(all_of) = schema.get("allOf").and_then(Value::as_array) {
        if all_of.len() == 1 {
            return resolve_type(&all_of[0], defs, shared, imports);
        }
    }

    // anyOf optional: [{ref/type}, {type: null}]
    if let Some(any_of) = schema.get("anyOf").and_then(Value::as_array) {
        let non_null: Vec<&Value> = any_of
            .iter()
            .filter(|s| s.get("type").and_then(Value::as_str) != Some("null"))
            .collect();
        if non_null.len() == 1 {
            let (t, m) = resolve_type(non_null[0], defs, shared, imports);
            let modifier = if m == "repeated" {
                "repeated".to_string()
            } else {
                "optional".to_string()
            };
            return (t, modifier);
        }
    }

    // type-array optional: ["string", "null"], ["integer", "null"]
    if let Some(type_arr) = schema.get("type").and_then(Value::as_array) {
        let non_null: Vec<&str> = type_arr
            .iter()
            .filter_map(Value::as_str)
            .filter(|&t| t != "null")
            .collect();
        if non_null.len() == 1 {
            let mut patched = schema.clone();
            patched["type"] = Value::String(non_null[0].to_string());
            let (t, m) = resolve_type(&patched, defs, shared, imports);
            let modifier = if m == "repeated" {
                "repeated".to_string()
            } else {
                "optional".to_string()
            };
            return (t, modifier);
        }
    }

    let typ = schema.get("type").and_then(Value::as_str).unwrap_or("");
    match typ {
        "string" => ("string".to_string(), String::new()),
        "boolean" => ("bool".to_string(), String::new()),
        "integer" => {
            let fmt = schema
                .get("format")
                .and_then(Value::as_str)
                .unwrap_or("int64");
            (int_format(fmt).to_string(), String::new())
        }
        "array" => {
            if let Some(items) = schema.get("items") {
                if items.is_object() {
                    let (t, _) = resolve_type(items, defs, shared, imports);
                    return (t, "repeated".to_string());
                }
            }
            // Tuple array — lose type info
            ("bytes".to_string(), "repeated".to_string())
        }
        // "object" and anything else
        _ => ("bytes".to_string(), String::new()),
    }
}

fn resolve_ref(
    name: &str,
    defs: &BTreeMap<String, Value>,
    shared: &BTreeMap<String, Value>,
    imports: &mut BTreeSet<String>,
) -> (String, String) {
    if is_string_newtype_name(name) {
        return ("string".to_string(), String::new());
    }
    if let Some(defn) = defs.get(name) {
        if is_string_newtype(defn) {
            return ("string".to_string(), String::new());
        }
    }
    let tn = sanitize_type_name(name);
    if shared.contains_key(name) {
        imports.insert(TYPES_PROTO_PATH.to_string());
        return (format!("{TYPES_PACKAGE}.{tn}"), String::new());
    }
    (tn, String::new())
}

// ─── Proto builder ──────────────────────────────────────────────

struct ProtoFile {
    package: String,
    imports: BTreeSet<String>,
    blocks: Vec<String>,
    names: BTreeSet<String>,
}

impl ProtoFile {
    fn new(package: &str) -> Self {
        Self {
            package: package.to_string(),
            imports: BTreeSet::new(),
            blocks: Vec::new(),
            names: BTreeSet::new(),
        }
    }

    fn add(&mut self, name: &str, text: &str) {
        if !self.names.contains(name) {
            self.names.insert(name.to_string());
            self.blocks.push(text.to_string());
        }
    }

    fn render(&self) -> String {
        let mut lines = vec![
            "syntax = \"proto3\";".to_string(),
            String::new(),
            format!("package {};", self.package),
        ];
        if !self.imports.is_empty() {
            lines.push(String::new());
            for imp in &self.imports {
                lines.push(format!("import \"{imp}\";"));
            }
        }
        for block in &self.blocks {
            lines.push(String::new());
            lines.push(block.clone());
        }
        lines.push(String::new());
        lines.join("\n")
    }
}

// ─── Code generators ────────────────────────────────────────────

fn gen_struct(
    name: &str,
    schema: &Value,
    defs: &BTreeMap<String, Value>,
    shared: &BTreeMap<String, Value>,
    pf: &mut ProtoFile,
) -> String {
    let tn = sanitize_type_name(name);
    let props = schema
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    let req: BTreeSet<String> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(Value::as_str)
                .map(String::from)
                .collect()
        })
        .unwrap_or_default();

    let mut lines = vec![format!("message {tn} {{")];
    for (i, (fname, fschema)) in props.iter().enumerate() {
        let (pt, mut modifier) = resolve_type(fschema, defs, shared, &mut pf.imports);
        if !req.contains(fname) && modifier.is_empty() {
            modifier = "optional".to_string();
        }
        let prefix = if modifier.is_empty() {
            String::new()
        } else {
            format!("{modifier} ")
        };
        lines.push(format!("  {prefix}{pt} {fname} = {};", i + 1));
    }
    lines.push("}".to_string());
    lines.join("\n")
}

fn gen_enum(name: &str, schema: &Value) -> String {
    let tn = sanitize_type_name(name);
    let pre = enum_prefix(&tn);
    let mut lines = vec![format!("enum {tn} {{"), format!("  {pre}_UNSPECIFIED = 0;")];
    if let Some(variants) = schema.get("enum").and_then(Value::as_array) {
        for (i, v) in variants.iter().enumerate() {
            if let Some(s) = v.as_str() {
                lines.push(format!("  {pre}_{} = {};", s.to_uppercase(), i + 1));
            }
        }
    }
    lines.push("}".to_string());
    lines.join("\n")
}

/// Resolve a single oneof variant's schema to a (`field_name`, `proto_type`) pair.
fn resolve_variant(
    vname: &str,
    vschema: &Value,
    tn: &str,
    defs: &BTreeMap<String, Value>,
    shared: &BTreeMap<String, Value>,
    pf: &mut ProtoFile,
) -> (String, String) {
    if let Some(r) = vschema.get("$ref").and_then(Value::as_str) {
        let ref_name = r.rsplit('/').next().unwrap_or("");
        if is_string_newtype_name(ref_name) || defs.get(ref_name).is_some_and(is_string_newtype) {
            return (vname.to_string(), "string".to_string());
        } else if shared.contains_key(ref_name) {
            pf.imports.insert(TYPES_PROTO_PATH.to_string());
            return (
                vname.to_string(),
                format!("{TYPES_PACKAGE}.{}", sanitize_type_name(ref_name)),
            );
        }
        return (vname.to_string(), sanitize_type_name(ref_name));
    }

    if is_empty_struct(vschema) {
        let mut msg = snake_to_pascal(vname);
        if pf.names.contains(&msg) {
            msg = format!("{tn}{msg}");
        }
        pf.add(&msg, &format!("message {msg} {{}}"));
        return (vname.to_string(), msg);
    }

    if is_struct(vschema) {
        let mut msg = snake_to_pascal(vname);
        if pf.names.contains(&msg) {
            msg = format!("{tn}{msg}");
        }
        let text = gen_struct(&msg, vschema, defs, shared, pf);
        pf.add(&msg, &text);
        return (vname.to_string(), msg);
    }

    if is_rust_enum(vschema) {
        let mut msg = snake_to_pascal(vname);
        if pf.names.contains(&msg) {
            msg = format!("{tn}{msg}");
        }
        let text = gen_oneof(&msg, vschema, defs, shared, pf);
        pf.add(&msg, &text);
        return (vname.to_string(), msg);
    }

    let typ_str = vschema.get("type").and_then(Value::as_str).unwrap_or("");
    let proto_type = match typ_str {
        "string" => "string".to_string(),
        "boolean" => "bool".to_string(),
        "integer" => {
            let fmt = vschema
                .get("format")
                .and_then(Value::as_str)
                .unwrap_or("int64");
            int_format(fmt).to_string()
        }
        _ => "bytes".to_string(),
    };
    (vname.to_string(), proto_type)
}

fn gen_oneof(
    name: &str,
    schema: &Value,
    defs: &BTreeMap<String, Value>,
    shared: &BTreeMap<String, Value>,
    pf: &mut ProtoFile,
) -> String {
    let tn = sanitize_type_name(name);
    let re = Regex::new(r"(?P<b>.)(?P<a>[A-Z])").unwrap();
    let oneof_name = re.replace_all(&tn, "${b}_${a}").to_lowercase();

    let mut fields: Vec<(String, String)> = Vec::new();

    let variants = schema
        .get("oneOf")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();

    for variant in &variants {
        let req: Vec<String> = variant
            .get("required")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(String::from)
                    .collect()
            })
            .unwrap_or_default();

        // String literal variant: {"type": "string", "enum": ["variant_name"]}
        if req.is_empty() {
            if variant.get("type").and_then(Value::as_str) == Some("string") {
                if let Some(e) = variant.get("enum").and_then(Value::as_array) {
                    if e.len() == 1 {
                        if let Some(vname) = e[0].as_str() {
                            let mut msg = snake_to_pascal(vname);
                            if pf.names.contains(&msg) {
                                msg = format!("{tn}{msg}");
                            }
                            pf.add(&msg, &format!("message {msg} {{}}"));
                            fields.push((vname.to_string(), msg));
                        }
                    }
                }
            }
            continue;
        }

        let vname = &req[0];
        let mut vschema = variant
            .get("properties")
            .and_then(|p| p.get(vname.as_str()))
            .cloned()
            .unwrap_or(Value::Object(serde_json::Map::new()));

        // Unwrap allOf single-ref
        while vschema
            .get("allOf")
            .and_then(Value::as_array)
            .is_some_and(|a| a.len() == 1)
        {
            vschema = vschema["allOf"][0].clone();
        }

        fields.push(resolve_variant(vname, &vschema, &tn, defs, shared, pf));
    }

    let mut lines = vec![
        format!("message {tn} {{"),
        format!("  oneof {oneof_name} {{"),
    ];
    for (i, (vname, vtype)) in fields.iter().enumerate() {
        lines.push(format!("    {vtype} {vname} = {};", i + 1));
    }
    lines.push("  }".to_string());
    lines.push("}".to_string());
    lines.join("\n")
}

fn gen_definition(
    name: &str,
    schema: &Value,
    defs: &BTreeMap<String, Value>,
    shared: &BTreeMap<String, Value>,
    pf: &mut ProtoFile,
) -> Option<String> {
    if is_string_newtype_name(name) || is_string_newtype(schema) {
        return None;
    }
    if is_empty_enum(schema) {
        return None;
    }
    if is_string_enum(schema) {
        return Some(gen_enum(name, schema));
    }
    if is_rust_enum(schema) {
        return Some(gen_oneof(name, schema, defs, shared, pf));
    }
    if is_struct(schema) {
        return Some(gen_struct(name, schema, defs, shared, pf));
    }
    if is_empty_struct(schema) {
        return Some(format!("message {} {{}}", sanitize_type_name(name)));
    }
    None
}

// ─── Definition helpers ─────────────────────────────────────────

fn merge_defs(schema: &Value) -> BTreeMap<String, Value> {
    let mut merged = BTreeMap::new();
    for sec in ["instantiate", "execute", "query", "migrate", "sudo"] {
        if let Some(s) = schema.get(sec).and_then(Value::as_object) {
            if let Some(defs) = s.get("definitions").and_then(Value::as_object) {
                for (k, v) in defs {
                    merged.insert(k.clone(), v.clone());
                }
            }
        }
    }
    if let Some(responses) = schema.get("responses").and_then(Value::as_object) {
        for rs in responses.values() {
            if let Some(defs) = rs.get("definitions").and_then(Value::as_object) {
                for (k, v) in defs {
                    merged.insert(k.clone(), v.clone());
                }
            }
        }
    }
    merged
}

fn find_shared(schemas: &BTreeMap<String, Value>) -> BTreeMap<String, Value> {
    // definition_name -> canonical_json -> set of contract paths
    let mut dm: HashMap<String, HashMap<String, BTreeSet<String>>> = HashMap::new();

    for (path, schema) in schemas {
        for (name, defn) in merge_defs(schema) {
            if is_string_newtype_name(&name) {
                continue;
            }
            let canonical = serde_json::to_string(&defn).unwrap_or_default();
            dm.entry(name)
                .or_default()
                .entry(canonical)
                .or_default()
                .insert(path.clone());
        }
    }

    let mut shared = BTreeMap::new();
    for (name, cm) in &dm {
        if cm.len() == 1 {
            let (canon, contracts) = cm.iter().next().unwrap();
            if contracts.len() >= 2 {
                if let Ok(val) = serde_json::from_str(canon) {
                    shared.insert(name.clone(), val);
                }
            }
        }
    }
    shared
}

fn needed_defs(section: &Value, defs: &BTreeMap<String, Value>, visited: &mut BTreeSet<String>) {
    match section {
        Value::Object(map) => {
            if let Some(r) = map.get("$ref").and_then(Value::as_str) {
                let ref_name = r.rsplit('/').next().unwrap_or("").to_string();
                if !visited.contains(&ref_name) {
                    visited.insert(ref_name.clone());
                    if let Some(d) = defs.get(&ref_name) {
                        needed_defs(d, defs, visited);
                    }
                }
                return;
            }
            for (k, v) in map {
                if k == "definitions" {
                    continue;
                }
                needed_defs(v, defs, visited);
            }
        }
        Value::Array(arr) => {
            for item in arr {
                needed_defs(item, defs, visited);
            }
        }
        _ => {}
    }
}

// ─── Contract discovery ─────────────────────────────────────────

struct ContractInfo {
    schema_path: String,
    package: String,
    proto_path: String,
}

fn discover_contracts(root: &Path) -> Vec<ContractInfo> {
    let pattern = root
        .join("contracts/*/*/src/bin/schema.rs")
        .to_string_lossy()
        .to_string();

    let mut contracts = Vec::new();
    let mut paths: Vec<PathBuf> = glob::glob(&pattern)
        .unwrap_or_else(|e| {
            eprintln!("glob error: {e}");
            std::process::exit(1);
        })
        .filter_map(Result::ok)
        .collect();
    paths.sort();

    for schema_rs in paths {
        // schema_rs = .../contracts/{category}/{name}/src/bin/schema.rs
        let contract_dir = schema_rs
            .parent() // bin/
            .and_then(Path::parent) // src/
            .and_then(Path::parent) // {name}/
            .unwrap();

        let schema_dir = contract_dir.join("schema");
        let schema_files: Vec<PathBuf> = glob::glob(&schema_dir.join("*.json").to_string_lossy())
            .ok()
            .map(|g| g.filter_map(Result::ok).collect())
            .unwrap_or_default();

        if schema_files.is_empty() {
            continue;
        }

        let schema_path = schema_files[0]
            .strip_prefix(root)
            .unwrap()
            .to_string_lossy()
            .to_string();

        let category = contract_dir
            .parent()
            .unwrap()
            .file_name()
            .unwrap()
            .to_string_lossy()
            .to_string();
        let name = contract_dir
            .file_name()
            .unwrap()
            .to_string_lossy()
            .to_string();
        let proto_name = name.replace('-', "_");

        let package = format!("euclid.{category}.{proto_name}.v1");
        let proto_path = format!("euclid/{category}/{proto_name}/v1/{proto_name}.proto");

        contracts.push(ContractInfo {
            schema_path,
            package,
            proto_path,
        });
    }
    contracts
}

// ─── File generators ────────────────────────────────────────────

fn generate_types(
    shared: &BTreeMap<String, Value>,
    all_defs: &BTreeMap<String, Value>,
) -> (String, String) {
    let empty = BTreeMap::new();
    let mut pf = ProtoFile::new(TYPES_PACKAGE);
    for (name, schema) in shared {
        if let Some(text) = gen_definition(name, schema, all_defs, &empty, &mut pf) {
            pf.add(&sanitize_type_name(name), &text);
        }
    }
    (TYPES_PROTO_PATH.to_string(), pf.render())
}

fn generate_contract(
    contract: &ContractInfo,
    schema: &Value,
    shared: &BTreeMap<String, Value>,
) -> (String, String) {
    let mut pf = ProtoFile::new(&contract.package);
    let defs = merge_defs(schema);

    // Entry points
    if let Some(inst) = schema.get("instantiate") {
        if is_struct(inst) {
            let text = gen_struct("InstantiateMsg", inst, &defs, shared, &mut pf);
            pf.add("InstantiateMsg", &text);
        }
    }

    if let Some(exe) = schema.get("execute") {
        if is_rust_enum(exe) {
            let text = gen_oneof("ExecuteMsg", exe, &defs, shared, &mut pf);
            pf.add("ExecuteMsg", &text);
        }
    }

    if let Some(qry) = schema.get("query") {
        if is_rust_enum(qry) {
            let text = gen_oneof("QueryMsg", qry, &defs, shared, &mut pf);
            pf.add("QueryMsg", &text);
        }
    }

    // Response types
    if let Some(responses) = schema.get("responses").and_then(Value::as_object) {
        for (rname, rschema) in responses {
            if !rschema.is_object() {
                continue;
            }
            let title_raw = rschema
                .get("title")
                .and_then(Value::as_str)
                .map_or_else(|| snake_to_pascal(rname), String::from);
            let title = sanitize_type_name(&title_raw);

            let mut rdefs = defs.clone();
            if let Some(d) = rschema.get("definitions").and_then(Value::as_object) {
                for (k, v) in d {
                    rdefs.insert(k.clone(), v.clone());
                }
            }

            if is_struct(rschema) {
                let text = gen_struct(&title, rschema, &rdefs, shared, &mut pf);
                pf.add(&title, &text);
            } else if is_rust_enum(rschema) {
                let text = gen_oneof(&title, rschema, &rdefs, shared, &mut pf);
                pf.add(&title, &text);
            } else {
                // Primitive or array response — wrap in a message
                let (pt, modifier) = resolve_type(rschema, &rdefs, shared, &mut pf.imports);
                let prefix = if modifier.is_empty() {
                    String::new()
                } else {
                    format!("{modifier} ")
                };
                pf.add(
                    &title,
                    &format!("message {title} {{\n  {prefix}{pt} value = 1;\n}}"),
                );
            }
        }
    }

    // Local definitions (not shared, not string newtypes)
    let mut all_needed = BTreeSet::new();
    for sec in ["instantiate", "execute", "query"] {
        if let Some(s) = schema.get(sec) {
            needed_defs(s, &defs, &mut all_needed);
        }
    }
    if let Some(responses) = schema.get("responses").and_then(Value::as_object) {
        for rschema in responses.values() {
            if rschema.is_object() {
                let mut rdefs = defs.clone();
                if let Some(d) = rschema.get("definitions").and_then(Value::as_object) {
                    for (k, v) in d {
                        rdefs.insert(k.clone(), v.clone());
                    }
                }
                needed_defs(rschema, &rdefs, &mut all_needed);
            }
        }
    }

    for dn in &all_needed {
        if is_string_newtype_name(dn) || shared.contains_key(dn) {
            continue;
        }
        let Some(definition) = defs.get(dn) else {
            continue;
        };
        if is_string_newtype(definition) {
            continue;
        }
        if let Some(text) = gen_definition(dn, definition, &defs, shared, &mut pf) {
            pf.add(&sanitize_type_name(dn), &text);
        }
    }

    (contract.proto_path.clone(), pf.render())
}

// ─── Main ───────────────────────────────────────────────────────

fn main() {
    let dry_run = std::env::args().any(|a| a == "--dry-run");

    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    let proto_dir = root.join("proto");

    let contracts = discover_contracts(root);
    if contracts.is_empty() {
        eprintln!("No contract schemas found. Generate them first:");
        eprintln!("  for d in contracts/*/*/; do [ -f \"$d/src/bin/schema.rs\" ] && (cd \"$d\" && cargo run --bin schema); done");
        std::process::exit(1);
    }

    println!("Discovered {} contracts", contracts.len());

    let mut schemas = BTreeMap::new();
    for c in &contracts {
        let content = fs::read_to_string(root.join(&c.schema_path)).unwrap_or_else(|e| {
            eprintln!("Failed to read {}: {e}", c.schema_path);
            std::process::exit(1);
        });
        let val: Value = serde_json::from_str(&content).unwrap_or_else(|e| {
            eprintln!("Failed to parse {}: {e}", c.schema_path);
            std::process::exit(1);
        });
        schemas.insert(c.schema_path.clone(), val);
    }

    let shared = find_shared(&schemas);
    let mut all_defs = BTreeMap::new();
    for s in schemas.values() {
        all_defs.extend(merge_defs(s));
    }

    println!("Found {} shared type definitions", shared.len());

    let mut outputs = Vec::new();

    // Shared types
    let (tp, tc) = generate_types(&shared, &all_defs);
    outputs.push((tp, tc));

    // Per-contract
    for contract in &contracts {
        let schema = &schemas[&contract.schema_path];
        let (cp, cc) = generate_contract(contract, schema, &shared);
        outputs.push((cp, cc));
    }

    let buf_yaml = "\
version: v2
modules:
  - path: .
    name: buf.build/euclidprotocol/contracts
lint:
  use:
    - STANDARD
breaking:
  use:
    - FILE
";

    if dry_run {
        for (path, content) in &outputs {
            println!("\n{}\n{path}\n{}", "=".repeat(60), "=".repeat(60));
            print!("{content}");
        }
    } else {
        for (path, content) in &outputs {
            let out = proto_dir.join(path);
            if let Some(parent) = out.parent() {
                fs::create_dir_all(parent).unwrap_or_else(|e| {
                    eprintln!("Failed to create dir: {e}");
                    std::process::exit(1);
                });
            }
            fs::write(&out, content).unwrap_or_else(|e| {
                eprintln!("Failed to write {path}: {e}");
                std::process::exit(1);
            });
            println!("  {path}");
        }
        fs::write(proto_dir.join("buf.yaml"), buf_yaml).unwrap_or_else(|e| {
            eprintln!("Failed to write buf.yaml: {e}");
            std::process::exit(1);
        });
        println!("  buf.yaml");
    }

    println!("\nGenerated {} proto files in proto/", outputs.len());
}
