[package]
name = "mock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.5.3" }
cw-storage-plus = "1.1.0"
itertools = "0.10"
cosmwasm-schema = "1.1"
cw-utils = "1.0"
thiserror = { workspace = true }
cw20 = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
anyhow = "1.0.79"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { version = "1.0.0", features = ["cosmwasm_1_2"] }
