[package]
name = "mock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
itertools = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-utils = { workspace = true }
thiserror = { workspace = true }
cw20 = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
anyhow = "1.0.79"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test = { workspace = true , features = ["cosmwasm_1_2"] }
