#!/usr/bin/env python3
"""Convert CosmWasm JSON Schema files to Protocol Buffer (.proto) definitions.

Reads contract schema JSON files generated by cosmwasm_schema::write_api!
and produces .proto files for publishing to buf.build.

Usage:
    python scripts/schema_to_proto.py           # Write to proto/
    python scripts/schema_to_proto.py --dry-run  # Print without writing

Generate schemas first:
    for d in contracts/*/*/; do [ -f "$d/src/bin/schema.rs" ] && (cd "$d" && cargo run --bin schema); done
"""

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent
PROTO_DIR = ROOT / "proto"


def discover_contracts():
    """Auto-discover contracts by scanning for schema JSON files.

    Derives proto package and output path from the directory structure:
      contracts/{category}/{name}/schema/{file}.json
      -> euclid.{category}.{name}.v1 / euclid/{category}/{name}/v1/{name}.proto
    """
    contracts = {}
    for schema_rs in sorted(ROOT.glob("contracts/*/*/src/bin/schema.rs")):
        contract_dir = schema_rs.parent.parent.parent
        schema_files = list(contract_dir.glob("schema/*.json"))
        if not schema_files:
            continue
        schema_path = str(schema_files[0].relative_to(ROOT))
        category = contract_dir.parent.name
        name = contract_dir.name
        # Normalize for proto (hyphens -> underscores)
        proto_name = name.replace("-", "_")
        pkg = f"euclid.{category}.{proto_name}.v1"
        proto_path = f"euclid/{category}/{proto_name}/v1/{proto_name}.proto"
        contracts[schema_path] = (pkg, proto_path)
    return contracts

TYPES_PACKAGE = "euclid.types.v1"
TYPES_PROTO_PATH = "euclid/types/v1/types.proto"

# CosmWasm types serialized as JSON strings -> proto string
STRING_NEWTYPES = {
    "Addr", "Binary", "Uint128", "Uint64", "Decimal",
    "Token", "ChainUid", "Timestamp",
}


# ─── Naming ──────────────────────────────────────────────────────

def snake_to_pascal(name):
    """manage_router_state -> ManageRouterState"""
    return "".join(w.capitalize() for w in name.split("_") if w)


def sanitize_type_name(name):
    """Pagination_for_Uint128 -> PaginationForUint128

    Replaces _for_, _of_, _and_ with PascalCase keywords, then capitalizes
    any remaining underscore-separated segments. Also capitalizes the char
    immediately after each keyword insertion to handle cases like
    Tuple_of_uint128 -> TupleOfUint128 (not TupleOfuint128).
    """
    # Replace keyword separators and capitalize the following char
    for old, new in [("_for_", "_For_"), ("_of_", "_Of_"), ("_and_", "_And_")]:
        name = name.replace(old, new)
    # Split on underscores and capitalize each segment
    return "".join(seg[0].upper() + seg[1:] if seg else "" for seg in name.split("_"))


def enum_prefix(pascal_name):
    """AdminType -> ADMIN_TYPE"""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", pascal_name).upper()


# ─── Schema classification ──────────────────────────────────────

def is_string_newtype(s):
    if s.get("type") == "string" and "enum" not in s:
        return True
    if "allOf" in s and len(s["allOf"]) == 1:
        ref = s["allOf"][0].get("$ref", "")
        return ref.split("/")[-1] in STRING_NEWTYPES
    return False


def is_string_enum(s):
    return (s.get("type") == "string"
            and isinstance(s.get("enum"), list) and len(s["enum"]) > 0)


def is_empty_enum(s):
    return s.get("type") == "string" and s.get("enum") == []


def _is_tagged_variant(v):
    """Check if a oneOf variant is externally-tagged (object with one required key)
    or a string literal variant (unit-like enum variant)."""
    if v.get("type") == "object" and len(v.get("required", [])) == 1:
        return True
    # String literal variant: {"type": "string", "enum": ["variant_name"]}
    if v.get("type") == "string" and isinstance(v.get("enum"), list) and len(v["enum"]) == 1:
        return True
    return False


def is_rust_enum(s):
    """CosmWasm externally-tagged enum: oneOf of tagged variants."""
    if "oneOf" not in s:
        return False
    return all(_is_tagged_variant(v) for v in s["oneOf"])


def is_struct(s):
    return s.get("type") == "object" and bool(s.get("properties"))


def is_empty_struct(s):
    return (s.get("type") == "object"
            and not s.get("properties")
            and s.get("additionalProperties") is False)


# ─── Type resolution ────────────────────────────────────────────

INT_FORMATS = {
    "uint64": "uint64", "uint128": "string", "int64": "int64",
    "int32": "int32", "uint8": "uint32", "uint16": "uint32", "uint32": "uint32",
}


def resolve_type(schema, defs, shared, imports):
    """Returns (proto_type, modifier) where modifier is '' | 'optional' | 'repeated'."""

    if "$ref" in schema:
        return _resolve_ref(schema["$ref"].split("/")[-1], defs, shared, imports)

    if "allOf" in schema and len(schema["allOf"]) == 1:
        return resolve_type(schema["allOf"][0], defs, shared, imports)

    # anyOf optional: [{ref/type}, {type: null}]
    if "anyOf" in schema:
        non_null = [s for s in schema["anyOf"] if s.get("type") != "null"]
        if len(non_null) == 1:
            t, m = resolve_type(non_null[0], defs, shared, imports)
            return (t, "repeated" if m == "repeated" else "optional")

    # type-array optional: ["string", "null"], ["integer", "null"]
    if isinstance(schema.get("type"), list):
        non_null = [t for t in schema["type"] if t != "null"]
        if len(non_null) == 1:
            t, m = resolve_type({**schema, "type": non_null[0]}, defs, shared, imports)
            return (t, "repeated" if m == "repeated" else "optional")

    typ = schema.get("type")
    if typ == "string":
        return ("string", "")
    if typ == "boolean":
        return ("bool", "")
    if typ == "integer":
        return (INT_FORMATS.get(schema.get("format", "int64"), "int64"), "")
    if typ == "array":
        items = schema.get("items")
        if isinstance(items, dict):
            t, _ = resolve_type(items, defs, shared, imports)
            return (t, "repeated")
        # Tuple array (fixed-size mixed types) — lose type info, use repeated bytes
        return ("bytes", "repeated")
    if typ == "object":
        return ("bytes", "")

    return ("bytes", "")


def _resolve_ref(name, defs, shared, imports):
    if name in STRING_NEWTYPES:
        return ("string", "")
    defn = defs.get(name, {})
    if is_string_newtype(defn):
        return ("string", "")
    tn = sanitize_type_name(name)
    if name in shared:
        imports.add(TYPES_PROTO_PATH)
        return (f"{TYPES_PACKAGE}.{tn}", "")
    return (tn, "")


# ─── Proto builder ──────────────────────────────────────────────

class ProtoFile:
    def __init__(self, package):
        self.package = package
        self.imports = set()
        self.blocks = []
        self.names = set()

    def add(self, name, text):
        if name not in self.names:
            self.names.add(name)
            self.blocks.append(text)

    def render(self):
        lines = ['syntax = "proto3";', "", f"package {self.package};"]
        if self.imports:
            lines.append("")
            for imp in sorted(self.imports):
                lines.append(f'import "{imp}";')
        for block in self.blocks:
            lines.extend(["", block])
        lines.append("")
        return "\n".join(lines)


# ─── Code generators ────────────────────────────────────────────

def gen_struct(name, schema, defs, shared, pf):
    """Generate proto message for a struct schema."""
    tn = sanitize_type_name(name)
    props = schema.get("properties", {})
    req = set(schema.get("required", []))
    lines = [f"message {tn} {{"]
    for i, (fname, fschema) in enumerate(props.items(), 1):
        pt, mod = resolve_type(fschema, defs, shared, pf.imports)
        if fname not in req and mod == "":
            mod = "optional"
        prefix = f"{mod} " if mod else ""
        lines.append(f"  {prefix}{pt} {fname} = {i};")
    lines.append("}")
    return "\n".join(lines)


def gen_enum(name, schema):
    """Generate proto enum from string enum."""
    tn = sanitize_type_name(name)
    pre = enum_prefix(tn)
    lines = [f"enum {tn} {{", f"  {pre}_UNSPECIFIED = 0;"]
    for i, v in enumerate(schema.get("enum", []), 1):
        lines.append(f"  {pre}_{v.upper()} = {i};")
    lines.append("}")
    return "\n".join(lines)


def gen_oneof(name, schema, defs, shared, pf):
    """Generate message with oneof for CosmWasm externally-tagged enum."""
    tn = sanitize_type_name(name)
    oneof_name = re.sub(r"(?<!^)(?=[A-Z])", "_", tn).lower()
    fields = []

    for variant in schema.get("oneOf", []):
        req = variant.get("required", [])

        # String literal variant: {"type": "string", "enum": ["variant_name"]}
        if (not req and variant.get("type") == "string"
                and isinstance(variant.get("enum"), list) and len(variant["enum"]) == 1):
            vname = variant["enum"][0]
            msg = snake_to_pascal(vname)
            if msg in pf.names:
                msg = f"{tn}{msg}"
            pf.add(msg, f"message {msg} {{}}")
            fields.append((vname, msg))
            continue

        if not req:
            continue
        vname = req[0]
        vschema = variant.get("properties", {}).get(vname, {})

        # Unwrap allOf single-ref
        while "allOf" in vschema and len(vschema["allOf"]) == 1:
            vschema = vschema["allOf"][0]

        if "$ref" in vschema:
            ref = vschema["$ref"].split("/")[-1]
            if ref in STRING_NEWTYPES or is_string_newtype(defs.get(ref, {})):
                fields.append((vname, "string"))
            elif ref in shared:
                pf.imports.add(TYPES_PROTO_PATH)
                fields.append((vname, f"{TYPES_PACKAGE}.{sanitize_type_name(ref)}"))
            else:
                fields.append((vname, sanitize_type_name(ref)))
        elif is_empty_struct(vschema):
            msg = snake_to_pascal(vname)
            if msg in pf.names:
                msg = f"{tn}{msg}"
            pf.add(msg, f"message {msg} {{}}")
            fields.append((vname, msg))
        elif is_struct(vschema):
            msg = snake_to_pascal(vname)
            if msg in pf.names:
                msg = f"{tn}{msg}"
            pf.add(msg, gen_struct(msg, vschema, defs, shared, pf))
            fields.append((vname, msg))
        elif is_rust_enum(vschema):
            msg = snake_to_pascal(vname)
            if msg in pf.names:
                msg = f"{tn}{msg}"
            pf.add(msg, gen_oneof(msg, vschema, defs, shared, pf))
            fields.append((vname, msg))
        elif vschema.get("type") == "string":
            fields.append((vname, "string"))
        elif vschema.get("type") == "boolean":
            fields.append((vname, "bool"))
        elif vschema.get("type") == "integer":
            fields.append((vname, INT_FORMATS.get(
                vschema.get("format", "int64"), "int64")))
        else:
            fields.append((vname, "bytes"))

    lines = [f"message {tn} {{", f"  oneof {oneof_name} {{"]
    for i, (vname, vtype) in enumerate(fields, 1):
        lines.append(f"    {vtype} {vname} = {i};")
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines)


def gen_definition(name, schema, defs, shared, pf):
    """Generate proto for a definition. Returns text or None."""
    if name in STRING_NEWTYPES or is_string_newtype(schema):
        return None
    if is_empty_enum(schema):
        return None
    if is_string_enum(schema):
        return gen_enum(name, schema)
    if is_rust_enum(schema):
        return gen_oneof(name, schema, defs, shared, pf)
    if is_struct(schema):
        return gen_struct(name, schema, defs, shared, pf)
    if is_empty_struct(schema):
        return f"message {sanitize_type_name(name)} {{}}"
    return None


# ─── Definition helpers ─────────────────────────────────────────

def merge_defs(schema):
    """Merge definitions from all sections of a contract schema."""
    merged = {}
    for sec in ("instantiate", "execute", "query", "migrate", "sudo"):
        s = schema.get(sec)
        if isinstance(s, dict):
            merged.update(s.get("definitions", {}))
    for rs in schema.get("responses", {}).values():
        if isinstance(rs, dict):
            merged.update(rs.get("definitions", {}))
    return merged


def find_shared(schemas):
    """Find definitions appearing identically in 2+ contracts."""
    dm = defaultdict(lambda: defaultdict(set))
    for path, schema in schemas.items():
        for name, defn in merge_defs(schema).items():
            if name in STRING_NEWTYPES:
                continue
            dm[name][json.dumps(defn, sort_keys=True)].add(path)
    shared = {}
    for name, cm in dm.items():
        if len(cm) == 1:
            canon, contracts = next(iter(cm.items()))
            if len(contracts) >= 2:
                shared[name] = json.loads(canon)
    return shared


def needed_defs(section, defs, visited=None):
    """Recursively collect all definition names referenced by a schema section."""
    if visited is None:
        visited = set()
    if not isinstance(section, dict):
        return visited
    if "$ref" in section:
        ref = section["$ref"].split("/")[-1]
        if ref not in visited:
            visited.add(ref)
            if ref in defs:
                needed_defs(defs[ref], defs, visited)
        return visited
    for k, v in section.items():
        if k == "definitions":
            continue
        if isinstance(v, dict):
            needed_defs(v, defs, visited)
        elif isinstance(v, list):
            for item in v:
                if isinstance(item, dict):
                    needed_defs(item, defs, visited)
    return visited


# ─── File generators ────────────────────────────────────────────

def generate_types(shared, all_defs):
    """Generate the shared types.proto file."""
    pf = ProtoFile(TYPES_PACKAGE)
    for name in sorted(shared):
        schema = shared[name]
        text = gen_definition(name, schema, all_defs, {}, pf)
        if text:
            pf.add(sanitize_type_name(name), text)
    return TYPES_PROTO_PATH, pf.render()


def generate_contract(path, schema, shared, contracts):
    """Generate a single contract's proto file."""
    pkg, proto_path = contracts[path]
    pf = ProtoFile(pkg)
    defs = merge_defs(schema)

    # Entry points
    inst = schema.get("instantiate")
    if inst and is_struct(inst):
        pf.add("InstantiateMsg", gen_struct("InstantiateMsg", inst, defs, shared, pf))

    exe = schema.get("execute")
    if exe and is_rust_enum(exe):
        pf.add("ExecuteMsg", gen_oneof("ExecuteMsg", exe, defs, shared, pf))

    qry = schema.get("query")
    if qry and is_rust_enum(qry):
        pf.add("QueryMsg", gen_oneof("QueryMsg", qry, defs, shared, pf))

    # Response types
    for rname, rschema in schema.get("responses", {}).items():
        if not isinstance(rschema, dict):
            continue
        title = sanitize_type_name(rschema.get("title", snake_to_pascal(rname)))
        rdefs = {**defs, **rschema.get("definitions", {})}
        if is_struct(rschema):
            pf.add(title, gen_struct(title, rschema, rdefs, shared, pf))
        elif is_rust_enum(rschema):
            pf.add(title, gen_oneof(title, rschema, rdefs, shared, pf))
        else:
            # Primitive or array response — wrap in a message
            pt, mod = resolve_type(rschema, rdefs, shared, pf.imports)
            prefix = f"{mod} " if mod else ""
            pf.add(title, f"message {title} {{\n  {prefix}{pt} value = 1;\n}}")

    # Local definitions (not shared, not string newtypes)
    all_needed = set()
    for sec in ("instantiate", "execute", "query"):
        s = schema.get(sec)
        if isinstance(s, dict):
            needed_defs(s, defs, all_needed)
    for rschema in schema.get("responses", {}).values():
        if isinstance(rschema, dict):
            rdefs = {**defs, **rschema.get("definitions", {})}
            needed_defs(rschema, rdefs, all_needed)

    for dn in sorted(all_needed):
        if dn in STRING_NEWTYPES or dn in shared:
            continue
        defn = defs.get(dn)
        if not defn or is_string_newtype(defn):
            continue
        text = gen_definition(dn, defn, defs, shared, pf)
        if text:
            pf.add(sanitize_type_name(dn), text)

    return proto_path, pf.render()


# ─── Main ───────────────────────────────────────────────────────

def main():
    dry_run = "--dry-run" in sys.argv

    contracts = discover_contracts()
    if not contracts:
        print("No contract schemas found. Generate them first:")
        print('  for d in contracts/*/*/; do [ -f "$d/src/bin/schema.rs" ] && (cd "$d" && cargo run --bin schema); done')
        sys.exit(1)

    print(f"Discovered {len(contracts)} contracts")

    schemas = {}
    for sp in contracts:
        with open(ROOT / sp) as f:
            schemas[sp] = json.load(f)

    shared = find_shared(schemas)
    all_defs = {}
    for s in schemas.values():
        all_defs.update(merge_defs(s))

    print(f"Found {len(shared)} shared type definitions")

    outputs = []

    # Shared types
    tp, tc = generate_types(shared, all_defs)
    outputs.append((tp, tc))

    # Per-contract
    for sp in contracts:
        cp, cc = generate_contract(sp, schemas[sp], shared, contracts)
        outputs.append((cp, cc))

    # buf configuration
    buf_yaml = """\
version: v2
modules:
  - path: .
    name: buf.build/euclidprotocol/contracts
lint:
  use:
    - STANDARD
breaking:
  use:
    - FILE
"""
    if dry_run:
        for path, content in outputs:
            print(f"\n{'=' * 60}\n{path}\n{'=' * 60}")
            print(content)
    else:
        for path, content in outputs:
            out = PROTO_DIR / path
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content)
            print(f"  {path}")
        (PROTO_DIR / "buf.yaml").write_text(buf_yaml)
        print("  buf.yaml")

    print(f"\nGenerated {len(outputs)} proto files in proto/")


if __name__ == "__main__":
    main()
